#!/bin/bash
#script minimal de lancement
#-compile pour recompiler
#aucun argument pour executer
export LD_LIBRARY_PATH="/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/runtime/glnx86:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/bin/glnx86:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/sys/os/glnx86:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/sys/java/jre/glnx86/jre/lib/i386/native_threads:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/sys/java/jre/glnx86/jre/lib/i386/server:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/sys/java/jre/glnx86/jre/lib/i386"
export XAPPLRESDIR="/usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/X11/app-defaults"

DIR=${0%/*}
cd $DIR

#on crée un lanceur si celui-ci n'existe pas
if [ ! -e $HOME/.local/share/applications/EnseaMap.desktop ]; then
{
echo "Création du lanceur";
echo -e "#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[fr]=$PWD/resources/Images/map_icone.png
Name[fr]=EnseaMap
Exec=sh -c $PWD/LAUNCH
Name=EnseaMap
Icon=$PWD/resources/Images/map_icone.png
" > $HOME/.local/share/applications/EnseaMap.desktop

chmod +x $HOME/.local/share/applications/EnseaMap.desktop	
}
fi


case $1 in
	"-compile" )
		if [ ! -d $PWD/classes ]; then
		{
			mkdir $PWD/classes
		}
		fi
		
		javac -d $PWD/classes -classpath /usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/toolbox/javabuilder/jar/javabuilder.jar:$PWD/resources/Jar/Panorama.jar:$PWD $PWD/src/*.java;; 

	""         )
		java -classpath /usr/local/MATLAB/MATLAB_Compiler_Runtime/v717/toolbox/javabuilder/jar/javabuilder.jar:$PWD/resources/Jar/Panorama.jar:$PWD/resources:$PWD:$PWD/classes Test;;
esac;		

exit 0;

